### ISSUE TITLE
import errer

### ISSUE THREAD

**Issue by xqfJohn** [pavlin-policar/openTSNE#253] opened 2023-11-12 03:43 UTC
![image](https://github.com/pavlin-policar/openTSNE/assets/84269762/0df9bdae-6823-4b4f-9891-9933e1ad26f1)

is it a error related to opentsne?

**Comment by pavlin-policar** [comment] 2023-11-12 09:05
Duplicate of #250.

Tl;dr: you need to run the jupyter server from the `examples` folder so that the folder gets added to the python path. You can also do this manually if you want.

**Closed by pavlin-policar** 2023-11-12 09:05 UTC
