### ISSUE TITLE
pandas DataFrames KeyError

### ISSUE THREAD

**Issue by fsvbach** [pavlin-policar/openTSNE#182] opened 2021-05-06 13:08 UTC
Hi Pavlin,

I worked with openTSNE using pandas DataFrames as input for a while and it worked fine. Suddenly I got a KeyError. It seems that for larger DataFrames openTSNE brekas down (other than sklearn). This minimal example will reproduce the error:
```
from openTSNE import TSNE
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randint(0,100,size=(2000, 4)), 
                  columns=list('ABCD'))

tsne = TSNE()

## adding this line solves the problem entirely
# df  = df.to_numpy()

## this works
tsne.fit(df[:500])

## this doesn't work
tsne.fit(df)
```

Do you have an idea what could cause this, and whether it's worth while to extend openTSNE for pandas DataFrames?

**Comment by pavlin-policar** [comment] 2021-05-09 15:45
Thanks for reporting the issue. I think this is definitely something that should work, although technically, it's currently unsupported. Perhaps the latest release broke this behaviour.

**Comment by pavlin-policar** [comment] 2021-05-11 14:53
Wait, so this works now? I don't think this should be working. I don't remember touching that particular part of the code. It makes sense that it fails, since indexing a pandas dataframe like that will select the column with name 0. A fix would also be fairly trivial -- just use `df.values` instead of `df`.

**Comment by dkobak** [comment] 2022-10-10 11:47
@pavlin-policar Based on the discussion above, this is not a bug. Rather, it's a feature request to add Pandas support to openTSNE. I guess this could be done along the lines of 

```
if isinstance(X, pd.DataFrame):
   X = X.values
```

however this will make openTSNE depend on Pandas, which I am not sure you want?

Can we use a hack like 
```
if not isinstance(X, np.ndarray):
   X = X.values
```

instead? Not sure what is the best practice.

**Comment by pavlin-policar** [comment] 2022-11-04 11:52
Yes, I don't want to drag pandas into the requirements. After letting this sit for a long time, I don't see a clear solution here. The hack seems brittle, and would fail with a weird error message if I were to pass in a list, for instance. Perhaps the best course of action here would be to add a type check throughout the code to make sure the input is always a type we know how to work with, i.e., a numpy array or a scipy sparse matrix.

But adding type checks might be tedious, so I might even be okay leaving things as they are. It's pretty clear from the docstrings and documentation what types of objects we expect, so I think leaving it up to the user to pass in the correct type may be completely fine here as well. I don't feel strongly about this either way.

**Comment by dkobak** [comment] 2022-11-08 17:08
I agree -- I am fine with closing this issue.

**Closed** 2022-11-09 12:16 UTC
Labels: bug
